Translating contributing.po
flaskcwg/flask-docs-fa pull request #11
Opened 2022-03-20 13:53 UTC by MDK84

<div dir="rtl">

# ترجمه [contributing.po]

## چک لیست ترجمه

* [x] چک باکس ورودی فایل مرتبط در README.md را با یک "x" پر کنید.
* [x] اگر اولین مترجم هستید، کامنت «FIRST AUTHOR <EMAIL@ADDRESS>» را در فایل «.po» به‌روزرسانی کنید.
* [x] مقدار فیلد «Last-Translator» را در فایل «.po» به‌روزرسانی کنید.
* [x]  «pre-commit» را اجرا کنید و مشکلات را برطرف کنید.
* [x] اسناد را به صورت محلی بسازید، (باید بدون هشدار یا خطا باشد).
* [ ] ترجمه ماشینی 

</div>

2022-03-23 14:33 UTC, mmdbalkhi requested changes

2022-03-23 14:33 UTC, mmdbalkhi commented on docs/locales/fa/LC_MESSAGES/contributing.po
> +msgstr "از توجه کردن شما به کمک به فلاسک ممنونیم!"
بهتر نیست اینطور ترجمه کنیم؟
»از توجه شما برای مشارکت در فلاسک ممنونیم»

2022-03-23 14:38 UTC, mmdbalkhi requested changes
بعضی از جا ها هم ترجمه نشده لطفا اونا رو هم ترجمه کنید مثل خط ۴۷

2022-03-23 14:55 UTC, mmdbalkhi commented
لطفا از ` بجای " یا ' استفاده کنید. این مشکل ایجاد می‌کنه برای بیلد مستندات.

2022-03-26 11:24 UTC, mmdbalkhi approved these changes
ترجمه هم خوبه ممنون @MDK84

2022-03-26 11:26 UTC, merged

2022-03-27 04:23 UTC, MDK84 commented
خیلی ببخشید بنده در سفر بودم شرمنده