Translated docs/shell.po
flaskcwg/flask-docs-fa pull request #27
Opened 2022-04-29 21:07 UTC by ja74d

ترجمه بخش shell

2022-04-30 10:07 UTC, mmdbalkhi commented
@MDK84 اگر براتون مقدور بود بررسی کنید. ممنون

2022-04-30 17:02 UTC, MDK84 requested changes

2022-04-30 17:04 UTC, mmdbalkhi requested changes
@ja74d لطفا اینجا نام و ایمیلتون رو قرار بدید.

2022-04-30 17:31 UTC, mmdbalkhi requested changes

2022-04-30 17:31 UTC, mmdbalkhi commented on docs/locales/fa/LC_MESSAGES/shell.po
>  # FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
لطفا اینجا اسم و ایمیلتون رو قرار بدید

2022-04-30 17:31 UTC, mmdbalkhi commented on docs/locales/fa/LC_MESSAGES/shell.po
> +"امکان می دهد دستورات پایتون را در زمان واقعی اجرا کنید و بلافاصله نتایج را "
بهتره که `real time` رو بهتره که `در آنی` یا `در آن واحد` ترجمه کنیم

2022-04-30 17:31 UTC, mmdbalkhi commented on docs/locales/fa/LC_MESSAGES/shell.po
> +"معمولاً از عبارت «with» برای فعال کردن این شی درخواست استفاده می‌کنید، اما در "
بهتره که اینجا عبارت `with` رو در داخل ` `` `` ` قرار بدید

2022-04-30 17:34 UTC, ja74d commented on docs/locales/fa/LC_MESSAGES/shell.po
> +"امکان می دهد دستورات پایتون را در زمان واقعی اجرا کنید و بلافاصله نتایج را "
ممنونم
اصلاح میکنم

2022-04-30 17:35 UTC, ja74d commented on docs/locales/fa/LC_MESSAGES/shell.po
> +"معمولاً از عبارت «with» برای فعال کردن این شی درخواست استفاده می‌کنید، اما در "
ممنونم
اصلاح میکنم

2022-04-30 17:39 UTC, ja74d commented
دوستان من اسم و ایمیل رو اضافه کردم
عبارت "with" رو هم اصلاح کردم
و ترجمه real time رو هم اصلاح کردم
تغییر دیگه‌ای مد نظرتون هست یا push کنم؟

2022-04-30 17:41 UTC, mmdbalkhi commented
> دوستان من اسم و ایمیل رو اضافه کردم عبارت "with" رو هم اصلاح کردم و ترجمه real time رو هم اصلاح کردم تغییر دیگه‌ای مد نظرتون هست یا push کنم؟

@ja74d ممنونم.
اینجا سینتکس Sphinx رو نقض کردید. لطفا اینو هم حل کنید(https://github.com/flaskcwg/flask-docs-fa/pull/27#discussion_r862342415)
مثلا اینکه یادتون رفته ` رو در ` ':meth:`~flask.ctx.RequestContext.push` ` کامل بنویسید.

2022-04-30 17:59 UTC, ja74d commented
attr:`~flask.Flask.test_request_context`
این متنی هستش که توی ترجمه استفاده شده
" : " رو باید کجا قرار بدم؟

2022-04-30 18:01 UTC, ja74d commented
متوجه شدم کجاست
الان اصلاح میکنم

2022-04-30 18:06 UTC, ja74d commented
اصلاحاتی که گفتید رو انجام دادم
متن خاصی برای commit در نظر دارید؟

2022-04-30 18:10 UTC, mmdbalkhi commented
> اصلاحاتی که گفتید رو انجام دادم متن خاصی برای commit در نظر دارید؟

مشکلی نیست هر متنی دوست داشتید قرار بدید البته میتونید از دستور زیر هم استفاده کنید تا کامیت قبلی ادیت بشه:

```sh
git add docs/locales/fa/LC_MESSAGES/shell.po
git commit --amend --no-edit
git push --force
```

2022-04-30 18:43 UTC, mmdbalkhi commented on docs/locales/fa/LC_MESSAGES/shell.po
>  #: ../../shell.rst:45
@ja74d فعلا این مشکلات مونده اگر ممکن باشه اینا رو هم حل کنید.
باید تمام عبارات داخل ترجمه برابر با متن باشند.

2022-05-19 11:03 UTC, merged

2022-05-19 11:03 UTC, mmdbalkhi commented
@ja74d ممنون از PR